# Generated by Django 5.2.3 on 2025-07-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='category',
            new_name='phone',
        ),
    ]
