# Generated by Django 5.2.3 on 2025-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
